### ISSUE TITLE
Deprecated identifiers in cloudflare-operator.git

### ISSUE THREAD

**Issue by PowerBootWS** [adyanth/cloudflare-operator#101]
Just an FYI, installation proceeds with the deprecated calls however the user will receive the following errors when installing using the kubectl cli:

COMMAND: kubectl apply -k https://github.com/adyanth/cloudflare-operator/config/default
WARNING: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
WARNING: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.

**Comment by adyanth** [comment]
Tracking this in #99
