### ISSUE TITLE
documentation outdates

### ISSUE THREAD

**Issue by imne** [adyanth/cloudflare-operator#102]
Hi please can you look at updating the documentation on https://github.com/adyanth/cloudflare-operator/blob/main/docs/getting-started.md not sure how to get started because in the documentation it says install https://github.com/adyanth/cloudflare-operator/config/default but getting a 404 for the operator install

**Comment by adyanth** [comment]
Did you try running `kubectl apply -k https://github.com/adyanth/cloudflare-operator/config/default`? Due to the way kubectl works, that link does not actually work if you try in the browser.

**Comment by imne** [comment]
thanks I just did a kubectl apply with the above url and it worked
