### ISSUE TITLE
Update default image

### ISSUE THREAD

**Issue by aaabramov** [adyanth/cloudflare-operator#105]
The current default image to run for a tunnel is `cloudflare/cloudflared:2022.12.1`.
I wonder if it can be safely updated to something like `cloudflare/cloudflared:2024.9.1`.
I think almost every consumer of the operator overrides the `.ClusterTunnel.spec.image`, but for newcomers, things will be more up-to-date by default.

**Comment by adyanth** [comment]
Yes, 2024.9.1 does work. Do you mind sending in a PR to update the default version?

**Comment by aaabramov** [comment]
@adyanth gladly, see #106

**Comment by adyanth** [comment]
Thanks!
