### ISSUE TITLE
Option to disable Cloudflare API integration

### ISSUE THREAD

**Issue by adyanth** [adyanth/cloudflare-operator#57]
With the introduction of [proxied wildcard domains](https://blog.cloudflare.com/wildcard-proxy-for-everyone/), the operator can be used in a mode where it does not talk to Cloudflare at all. Users can manually set a wildcard CNAME to whichever tunnel they create and let the operator handle the dynamic configuration of `cloudflared`.

This can be a `Tunnel`/`ClusterTunnel` CRD spec to disable DNS updates.

**Comment by adyanth** [comment]
It makes more sense to disable DNS updates rather than complete API communication (at least right now, with the use case in #70).

**Comment by danielkza** [comment]
It seems I still need to create a zone and define a domain in a `ClusterTunnel` even if I dont want the operator to manage DNS at all, why is that the case?
