### ISSUE TITLE
Getting Unauthorized for Existing tunnel.

### ISSUE THREAD

**Issue by drpdishant** [adyanth/cloudflare-operator#64]
Can you please put some guidance regarding how to connect to an existing tunnel, managed with Zero Trust Dashboard.

For the credentials.json I am using the output of cloudflared tunnel token <tunnel-id> , also I tried using the tunnel secret from that file to authorize with the tunnel. According to the cloudflare document its the only way to get authentication details for existing tunnel.

**Comment by adyanth** [comment]
Hey @drpdishant connecting to an existing tunnel is possible by setting either the `CLOUDFLARE_TUNNEL_CREDENTIAL_FILE` or `CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET` in the secret referred by `tunnel.spec.cloudflare.secret`.

If using `CLOUDFLARE_TUNNEL_CREDENTIAL_FILE`, the whole file content (base64 encoded for k8s secret) should be used. If using `CLOUDFLARE_TUNNEL_CREDENTIAL_SECRET`, set it to the (base64 encoded) `TunnelSecret` field from the credential.json file.

But, tunnels managed by the Zero Trust Dashboard have not been tested, and might not work.
It is in the roadmap to support managed tunnels by making use of the Cloudflare APIs for configuration. See https://github.com/adyanth/cloudflare-operator/issues/47#issuecomment-1121933699

**Comment by drpdishant** [comment]
Got it
