### ISSUE TITLE
Migrate to cloudflare-go

### ISSUE THREAD

**Issue by adyanth** [adyanth/cloudflare-operator#7]
Currently the Cloudflare API actions are done manually. It should be moved to the supported [`cloudflare-go`](https://pkg.go.dev/github.com/cloudflare/cloudflare-go) library for interacting with the v4 API.

**Comment by adyanth** [comment]
Keeping this pending till it comes out of beta. `cloudflare-go` is still not fully feature compatible with the API. 

Ex: https://github.com/cloudflare/cloudflare-go/issues/791

**Comment by dudo** [comment]
Seems this issue can be closed?
