### ISSUE TITLE
Log timestamps are in 'epoch` format.

### ISSUE THREAD

**Issue by matthewhembree** [adyanth/cloudflare-operator#87]
This is painful to get logging (Grok parsing) setup --in Datadog at least... for me.

It seems that when you use [opts.BindFlags](https://github.com/adyanth/cloudflare-operator/blob/c38e0cc14dceef41729f8f9852c5e3743d392bff/main.go#L67), the controller-runtime/zap [default](https://github.com/kubernetes-sigs/controller-runtime/blob/a784ee78d04bdf216006adfbc313328a0aded88a/pkg/log/zap/zap.go#L219-L220) of `RFC3339TimeEncoder` will be [changed](https://github.com/kubernetes-sigs/controller-runtime/blob/a784ee78d04bdf216006adfbc313328a0aded88a/pkg/log/zap/zap.go#L298) to `epoch`. 🤦 

Personally, I don't need epoch in cluster. I suppose it might be more useful in local development, so the flag `--zap-time-encoding=epoch` could be passed to manager.

One could also (even myself) use a Kustomize patch to pass the flag into manager.

Existing:
```
1.687317215031635e+09   INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
1.687317215032804e+09   INFO    setup   starting manager
1.687317215033797e+09   INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
1.687317215033952e+09   INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
```

Proposed:
```
2023-06-20T22:14:02-05:00       INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
2023-06-20T22:14:02-05:00       INFO    setup   starting manager
2023-06-20T22:14:02-05:00       INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
2023-06-20T22:14:02-05:00       INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
```

---
PR incoming.

Thanks!

**Comment by adyanth** [comment]
I never noticed the timestamps, good catch!
