### ISSUE TITLE
Reach API-Server through cloudflared

### ISSUE THREAD

**Issue by bgervan** [adyanth/cloudflare-operator#94]
Hi, 
did anyone try to reach api server service with cloudflared?

I tried with added hostnames to https://docs.k3s.io/cli/server#listeners tls-sans, but no luck. 
Still getting `Unable to connect to the server: x509: certificate signed by unknown authority`

What am I missing? Tried with tls and without.

```---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: cloudflare-tunnel-apiserver
subjects:
  - name: kubernetes
    spec:
      fqdn: kubernetes.example.com
      noTlsVerify: true
tunnelRef:
  kind: ClusterTunnel
  name: k3s-cluster-tunnel
 ```

**Comment by adyanth** [comment]
I just spun up a k8s cluster with docker desktop, installed the operator and applied your exact config. It works fine for me. The below reponse is indeed from the K8s API server.
<img width="605" alt="Screenshot 2023-11-05 at 7 38 02 AM" src="https://github.com/adyanth/cloudflare-operator/assets/33192449/56fc0b59-be58-4472-b33a-d4ac95b1b081">
