### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by felinto-dev** [adyanth/cloudflare-operator#97]
https://github.com/adyanth/cloudflare-operator/blob/main/docs/getting-started.md

Could you please fix the documentation ?

`kubectl apply -k https://github.com/adyanth/cloudflare-operator/config/default`

This link does not exists: `https://github.com/adyanth/cloudflare-operator/config/default`

**Comment by adyanth** [comment]
Works fine for me. The link wont open in your browser but the kubectl apply will work. It uses a different format.
